#!/usr/bin/env python
import sys
import fire
import Cocoa
from pathlib import Path

def change_icon_for_file(image: str, file: str):
    workspace = Cocoa.NSWorkspace.sharedWorkspace()
    workspace.setIcon_forFile_options_(
        Cocoa.NSImage.alloc().initWithContentsOfFile_(image),
        file, 
        0
    )

def change_icon(image_path: str, folder_path: str, file_glob_pattern: str = '*', recursive: bool = False):
    '''Change the icon of a file / folder or a set of sub files / folders recursively using file_glob_pattern and the recurssive flag'''
    if recursive:
        for file_path in Path(folder_path).rglob(file_glob_pattern):
            change_icon_for_file(image_path, file_path)
    else:
        change_icon_for_file(image_path, folder_path)
        

fire.Fire(change_icon)
